# GitHub Pages configuration for groover.life portfolio
title: "Christian Groover (@cgroovertech) - DevOps Portfolio"
description: "Self-taught DevOps engineer showcasing enterprise infrastructure with quantified outcomes."
author: "Christian Groover"
email: "contact@groover.life"
url: "https://cgroovertech.github.io/groover.life"
baseurl: "/groover.life"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Exclude files from build
exclude:
  - README.md
  - RESTRUCTURE_PLAN.md
  - .gitignore
  - Gemfile
  - Gemfile.lock

# Collections for organized content
collections:
  showcase:
    output: true
    permalink: /:collection/:name/
  case-studies:
    output: true
    permalink: /:collection/:name/

# Default layout for collections
defaults:
  - scope:
      path: "content/showcase"
      type: "showcase"
    values:
      layout: "default"
  - scope:
      path: "content/case-studies" 
      type: "case-studies"
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO and social media
github:
  username: cgroovertech
  repository_url: https://github.com/cgroovertech/groover.life

# Social links
social:
  name: Christian Groover
  links:
    - https://github.com/cgroovertech
    - https://github.com/cgroovertech/groover.life
